### ISSUE TITLE
Generic Unifiable instance

### ISSUE THREAD

**Issue by feuerbach** [wrengr/unification-fd#3]
Hi wren,

I am starting to use unification-fd in a new project, and I find writing a Unifiable instance by hand is quite tedious. I am surprised that there aren't any generic implementations of it that I could find.

I think it should be doable with GHC Generics.

So I have a few questions:

1. Do you happen to know any generic implementations? Did I miss something?
2. Is it a bad idea? :)
3. If I manage to write one, would you be open to including it in the package?

**Comment by wrengr** [comment]
Hi,

I've used it with generic-style stuff before, for my own projects; but those were with my own generic framework rather than any of the popular ones. There are two main concerns to bear in mind.

First is performance, which depends primarily on the particular generics framework you use. The original/pre-published version of this code used to only be for generics; but part of the reason for switching to use type classes is so folks can give their own flattened implementations for better performance. Though this is a concern in production code, it should be fine for most non-production code (plus, generics libraries have been getting better about these issues over the years).

The second concern is to bear in mind "non-standard" functors. For example, the standard notion of product will require everything to align exactly; but there are also other notions of product which can allow things to be reordered, duplicated, missing, etc. This is part of why the output type for zipMatch is so complicated/strange, with the `Either` et al. Most FP-oriented generics frameworks don't provide these sorts of functors, but they definitely come up in logic-programming circles. So the big concern here is not to force folks into using a particular generics framework which would prohibit these sorts of things.

Re the PR, from a quick look it doesn't seem to pull in anything too scary, so I'm game :) Will take a longer look tomorrow.

**Comment by feuerbach** [comment]
Oh yeah, I totally agree that the user should be able to write their own `zipMatch`. This is only about providing a sensible default implementation, which I think will suffice most of the time (even for production uses like DSLs).

**Comment by wrengr** [comment]
I had a few issues with the PR, but things should be fixed up now. If you want to play around with it and make sure it still works on your end, I can package it up and publish later tonight or sometime tomorrow

**Comment by wrengr** [comment]
@feuerbach also, if you know why [the Stack stuff is failing](https://travis-ci.org/wrengr/unification-fd/builds/244333055), let me know. I don't use Stack so I've no idea why that's failing

**Comment by feuerbach** [comment]
Yes, it works here.

You seem to have resolved the stack problems, is that right?

**Comment by wrengr** [comment]
Yeah, I fixed it. The template was missing a `stack init`
